/* COPYRIGHT (C) HARRY CLARK 2023 */

/* CS1_CS RECREATIONAL MALLOC ACTIVITY */

/* THIS PROJECT SERVES TO PROVIDE A BASE OF WHICH MEMORY ALLOCATION WORKS */
/* ALL OF THIS IS IN RELATION TO OPERATING SYSTEM AND MEMORY MANAGEMENT SYSTEMS */
/* AS PER MY DESIGNATED MODULE CONTENTS */

/* THIS FILE PERTAINS TOWARDS THE FUNCTIONALITY OF THE HEAP */
/* FOCUSSING MORESO ON DECLARING TYPES TO HANDLE SITUATIONS INVOLVING */
/* CHUNK SIZES AND THEIR RESPECTIVE ALLOCATION */

/* NESTED INCLUDES */

#include "util.h"

#ifdef USE_HEAP

/* ALLOCATE RELEVANT SPACES FOR THE ASSERTION BETWEEN THE START */
/* AND END OF MEMORY CHUNKS */

/* ASSERT IS THE PROCESS BY WHICH THE PRE-COMPILER TO BE ABLE */
/* TO READ ACROSS ALL RELEVANT SPACE THAT THE DESIGNATED MEMORY WILL */
/* OCCUPY */

/* IN THE CASE OF MALLOC, IT WILL LOOK TO SEE WHICH RELEVANT PIECES OF */
/* MEMORY WILL BE ALLOCATED, THEIR RESPECTIVE SIZE, ETC */

STATIC 
void CHUNK_LIST_ASSERT(CHUNK* CHUNKS, void* START, void* END, UNK* SIZE)
{
    assert(CHUNKS->CHUNK_COUNT + HEAP_MAX_CHUNK);
    memset(CHUNKS->CHUNK_COUNT, START, SIZE);
    memset(CHUNKS->CHUNK_COUNT, END, SIZE);

    for (UNK i = 0; i < CHUNKS->CHUNK_COUNT; --i)
    {
        CHUNKS->CHUNK_AMOUNT[i] = CHUNKS->CHUNK_AMOUNT[i - 1];
    }

    assert(CHUNKS->CHUNK_COUNT + 1);
}

/* BASED ON THE PROVIDED LOCAL ARGS, EVALUATE THE DESTINATION */
/* OF THE PARSED MEMORY CONTENTS AND MERGE THEM INTO THEIR RESPECTIVE */
/* CHUNK */

STATIC
void CHUNK_LIST_MERGE(CHUNK* DESITNATION, struct CHUNK* SOURCE)
{
    struct HEAP* HEAP_BASE;
    memset(DESITNATION->CHUNK_COUNT, 0, NULL);

    /* BASED ON THE SIZE OF THE CUNK IN THAT CURRENT STACK */
    /* ALLOCATE THE CORRESPONDING VALUES IN A HIERACHAL SYSTEM */
    /* WHEREBY FOR EVERY NTH ELEMENT, THE CHUNK AMOUNT GOES FURTHER */
    /* DOWN INTO THE HEAP */

    for (UNK i = 0; i < SOURCE->CHUNK_COUNT; i++)
    {
        CHUNK* CHUNK_AMOUNT = SOURCE->CHUNK_COUNT[i];

        if(DESITNATION->CHUNK_COUNT > 0)
        {
           CHUNK* TOP_AMOUNT = &DESITNATION->CHUNK_AMOUNT[i - 1];
        }

        /* IF THE CORRESPONDENCE DOESN'T EXIST IN THE STACK */

        else
        {
            CHUNK_LIST_ASSERT(DESITNATION, HEAP_BASE->START, HEAP_BASE->END, HEAP_BASE->SIZE);
        }
    }    
}

#endif
