/* COPYRIGHT (C) HARRY CLARK 2023 */

/* CS1_CS RECREATIONAL MALLOC ACTIVITY */

/* THIS PROJECT SERVES TO PROVIDE A BASE OF WHICH MEMORY ALLOCATION WORKS */
/* ALL OF THIS IS IN RELATION TO OPERATING SYSTEM AND MEMORY MANAGEMENT SYSTEMS */
/* AS PER MY DESIGNATED MODULE CONTENTS */

/* THIS FILE PERTAINS TOWARDS THE FUNCTIONALITY OF THE HEAP */
/* FOCUSSING MORESO ON DECLARING TYPES TO HANDLE SITUATIONS INVOLVING */
/* CHUNK SIZES AND THEIR RESPECTIVE ALLOCATION */

/* NESTED INCLUDES */

#include "util.h"

#ifdef USE_HEAP

/* ALLOCATE RELEVANT SPACES FOR THE ASSERTION BETWEEN THE START */
/* AND END OF MEMORY CHUNKS */

/* ASSERT IS THE PROCESS BY WHICH THE PRE-COMPILER TO BE ABLE */
/* TO READ ACROSS ALL RELEVANT SPACE THAT THE DESIGNATED MEMORY WILL */
/* OCCUPY */

/* IN THE CASE OF MALLOC, IT WILL LOOK TO SEE WHICH RELEVANT PIECES OF */
/* MEMORY WILL BE ALLOCATED, THEIR RESPECTIVE SIZE, ETC */

STATIC 
void CHUNK_LIST_ASSERT(const CHUNK* CHUNKS, void* START, void* END, UNK* SIZE)
{
    assert(CHUNKS->CHUNK_COUNT + HEAP_MAX_CHUNK);
    CHUNKS->CHUNK_AMOUNT[CHUNKS->CHUNK_COUNT] = START;
    CHUNKS->CHUNK_AMOUNT[CHUNKS->CHUNK_COUNT] = END;
}

#endif